type BaseThemeVars = {
  // Color Palette
  black?: string
  white?: string
  gray1?: string
  gray2?: string
  gray3?: string
  gray4?: string
  gray5?: string
  gray6?: string
  gray7?: string
  gray8?: string
  red?: string
  blue?: string
  orange?: string
  orangeDark?: string
  orangeLight?: string
  green?: string

  // Gradient Colors
  gradientRed?: string
  gradientOrange?: string

  // Component Colors
  primaryColor?: string
  primaryColorLight3?: string
  primaryColorLight5?: string
  primaryColorLight7?: string
  primaryColorLight8?: string
  primaryColorLight9?: string
  primaryColorDark2?: string
  successColor?: string
  successColorLight3?: string
  successColorLight5?: string
  successColorLight8?: string
  successColorLight9?: string
  successColorDark2?: string
  infoColor?: string
  infoColorLight3?: string
  infoColorLight5?: string
  infoColorLight8?: string
  infoColorLight9?: string
  infoColorDark2?: string
  dangerColor?: string
  dangerColorLight3?: string
  dangerColorLight5?: string
  dangerColorLight8?: string
  dangerColorLight9?: string
  dangerColorDark2?: string
  warningColor?: string
  warningColorLight3?: string
  warningColorLight5?: string
  warningColorLight8?: string
  warningColorLight9?: string
  warningColorDark2?: string
  bgColor?: string
  bgColorOverlay?: string
  textColor?: string
  textColor2?: string
  textColor3?: string
  textColorPrimary?: string
  textColorRegular?: string
  textColorSecondary?: string
  textColorPlaceholder?: string
  textColorDisabled?: string
  borderColorLight?: string
  borderColorLighter?: string
  borderColorExtraLight?: string
  fillColor?: string
  fillColorLight?: string
  fillColorLighter?: string
  fillColorBlank?: string
  boxShadowLight?: string
  activeColor?: string
  activeOpacity?: number
  disabledOpacity?: number
  disabledBgColor?: string
  disabledTextColor?: string
  disabledBorderColor?: string
  overlayColorLight?: string
  overlayColorLighter?: string
  maskColorExtraLight?: string
  background?: string
  background2?: string
  background3?: string

  // Padding
  paddingBase?: string
  paddingXs?: string
  paddingSm?: string
  paddingMd?: string
  paddingLg?: string
  paddingXl?: string

  // Font
  fontWeightPrimary?: number
  fontBold: number
  fontSizeXs?: string
  fontSizeSm?: string
  fontSizeMd?: string
  fontSizeLg?: string
  lineHeightXs?: string
  lineHeightSm?: string
  lineHeightMd?: string
  lineHeightLg?: string
  baseFont?: string
  priceFont?: string

  // Animation
  durationBase?: string
  durationFast?: string
  durationFunctionEaseInOutBezier?: string
  durationFunctionFastBezier?: string
  durationMdFade?: string
  durationFadeLinear?: string
  durationColor?: string
  easeOut?: string
  easeIn?: string
  componentSizeLarge?: string
  componentSize?: string
  componentSizeSmall?: string

  // Border
  borderWidth?: string
  borderStyle?: string
  borderColor?: string
  borderColorHover?: string
  border?: string
  radiusSm?: string
  radiusMd?: string
  radiusLg?: string
  radiusMax?: string
}

export type ConfigProviderThemeVars = BaseThemeVars &
  import('../action-bar').ActionBarThemeVars &
  import('../action-bar-button').ActionBarButtonThemeVars &
  import('../action-bar-icon').ActionBarIconThemeVars &
  import('../aside').AsideThemeVars &
  import('../avatar').AvatarThemeVars &
  import('../badge').BadgeThemeVars &
  import('../button').ButtonThemeVars &
  import('../calendar').CalendarVars &
  import('../card').CardThemeVars &
  import('../carousel').CarouselThemeVars &
  import('../cell').CellThemeVars &
  import('../cell-group').CellGroupThemeVars &
  import('../checkbox').CheckboxThemeVars &
  import('../collapse-item').CollapseItemThemeVars &
  import('../color-picker').ColorPickerThemeVars &
  import('../count-down').CountDownThemeVars &
  import('../dialog').DialogThemeVars &
  import('../divider').DividerThemeVars &
  import('../dropdown').DropdownThemeVars &
  import('../dynamic-tags').DynamicTagsThemeVars &
  import('../empty').EmptyThemeVars &
  import('../footer').FooterThemeVars &
  import('../grid-item').GridItemThemeVars &
  import('../header').HeaderThemeVars &
  import('../image').ImageThemeVars &
  import('../image-preview').ImagePreviewThemeVars &
  import('../input').InputThemeVars &
  import('../input-number').InputNumberThemeVars &
  import('../list').ListThemeVars &
  import('../loading').LoadingThemeVars &
  import('../loading-bar').LoadingBarThemeVars &
  import('../main').MainThemeVars &
  import('../mention').MentionThemeVars &
  import('../menu').MenuThemeVars &
  import('../message').MessageThemeVars &
  import('../nav-bar').NavBarThemeVars &
  import('../notify').NotifyThemeVars &
  import('../overlay').OverlayThemeVars &
  import('../pagination').PaginationThemeVars &
  import('../popover').PopoverThemeVars &
  import('../popup').PopupThemeVars &
  import('../progress').ProgressThemeVars &
  import('../pull-refresh').PullRefreshThemeVars &
  import('../radio').RadioThemeVars &
  import('../scrollbar').ScrollbarThemeVars &
  import('../select').SelectThemeVars &
  import('../skeleton').SkeletonThemeVars &
  import('../slider').SliderThemeVars &
  import('../step').StepThemeVars &
  import('../steps').StepsThemeVars &
  import('../sticky').StickyThemeVars &
  import('../switch').SwitchThemeVars &
  import('../table').TableThemeVars &
  import('../tabs').TabsThemeVars &
  import('../tabs-menu').TabsMenuThemeVars &
  import('../tabs-menu-item').TabsMenuItemThemeVars &
  import('../tag').TagThemeVars &
  import('../time-picker-pc').TimePickerPcThemeVars &
  import('../tooltip').TooltipThemeVars &
  import('../tree').TreeThemeVars &
  import('../tree-select-pc').TreeSelectPcThemeVars &
  import('../upload').UploadThemeVars &
  import('../watermark').WatermarkThemeVars
