export type ConfigProviderThemeVars =
  import('../action-bar').ActionBarThemeVars &
    import('../action-bar-button').ActionBarButtonThemeVars &
    import('../action-bar-icon').ActionBarIconThemeVars &
    import('../aside').AsideThemeVars &
    import('../avatar').AvatarThemeVars &
    import('../badge').BadgeThemeVars &
    import('../button').ButtonThemeVars &
    import('../card').CardThemeVars &
    import('../cell').CellThemeVars &
    import('../cell-group').CellGroupThemeVars &
    import('../checkbox').CheckboxThemeVars &
    import('../collapse-item').CollapseItemThemeVars &
    import('../color-picker').ColorPickerThemeVars &
    import('../count-down').CountDownThemeVars &
    import('../date-picker-pc').DatePickerPcVars &
    import('../dialog').DialogThemeVars &
    import('../divider').DividerThemeVars &
    import('../dropdown').DropdownThemeVars &
    import('../empty').EmptyThemeVars &
    import('../footer').FooterThemeVars &
    import('../grid-item').GridItemThemeVars &
    import('../header').HeaderThemeVars &
    import('../image').ImageThemeVars &
    import('../image-preview').ImagePreviewThemeVars &
    import('../input').InputThemeVars &
    import('../input-number').InputNumberThemeVars &
    import('../list').ListThemeVars &
    import('../loading').LoadingThemeVars &
    import('../main').MainThemeVars &
    import('../menu').MenuThemeVars &
    import('../message').MessageThemeVars &
    import('../nav-bar').NavBarThemeVars &
    import('../notify').NotifyThemeVars &
    import('../overlay').OverlayThemeVars &
    import('../pagination').PaginationThemeVars &
    import('../picker').PickerThemeVars &
    import('../picker-group').PickerGroupThemeVars &
    import('../popover').PopoverThemeVars &
    import('../popup').PopupThemeVars &
    import('../progress').ProgressThemeVars &
    import('../pull-refresh').PullRefreshThemeVars &
    import('../radio').RadioThemeVars &
    import('../scrollbar').ScrollbarThemeVars &
    import('../select').SelectThemeVars &
    import('../skeleton').SkeletonThemeVars &
    import('../slide-bar').SlideBarThemeVars &
    import('../slider').SliderThemeVars &
    import('../step').StepThemeVars &
    import('../steps').StepsThemeVars &
    import('../sticky').StickyThemeVars &
    import('../swipe').SwipeThemeVars &
    import('../switch').SwitchThemeVars &
    import('../table').TableThemeVars &
    import('../tabs').TabsThemeVars &
    import('../tabs-menu').TabsMenuThemeVars &
    import('../tabs-menu-item').TabsMenuItemThemeVars &
    import('../tag').TagThemeVars &
    import('../time-picker-pc').TimePickerPcThemeVars &
    import('../tooltip').TooltipThemeVars &
    import('../tree').TreeThemeVars &
    import('../tree-select-pc').TreeSelectPcThemeVars &
    import('../upload').UploadThemeVars
