name: Deploy V4 Site

on:
  push:
    branches: [master]
    paths:
      - 'packages/ryxon-docs/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          ref: 'master'

      - name: Install pnpm
        run: npm i pnpm@7 -g

      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Site
        run: npm run build:site

      - name: Deploy for GitHub 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: master
          folder: packages/ryxon-docs/.vuepress/dist/
          token: ${{ secrets.RYXON_UI_TOKEN }}
          repository-name: ryxon-ui/ryxon-ui.github.io
          clean: false
